### ISSUE TITLE
Incorrect usage of Capital

### ISSUE THREAD

**Issue by SOF3** [XanderID-MC/EconomyEnchant#4]
- `$api->completeConfig` runs asynchronously. Calling `CapitalSelector` during startup will access an uninitialized variable.
- This is not how you use labels. Labels are designed for **searching**, so each label should contain only one information.

I will send a pull request to fix these issues shortly.

**Comment by XanderID** [comment]
sorry if it's troublesome and Thank you SOF3 :)

**Comment by SOF3** [comment]
I don't understand what's the point of the `CapitalSelector` class though. Why not jus tput it inside the capital provider class?

**Comment by XanderID** [comment]
I've tried and the Selector is always null on construct, Is it because every time I buy an enchant, it loads a new Provider?
https://github.com/MulqiGaming64/EconomyEnchant/blob/ed83bf1dedd278c62df0e0ace2575951b750b144/src/MulqiGaming64/EconomyEnchant/EconomyEnchant.php#L686

**Comment by SOF3** [comment]
> I've tried and the Selector is always null on construct, Is it because every time I buy an enchant, it loads a new Provider?
> 
> https://github.com/MulqiGaming64/EconomyEnchant/blob/ed83bf1dedd278c62df0e0ace2575951b750b144/src/MulqiGaming64/EconomyEnchant/EconomyEnchant.php#L686

Capital::api() is not run immediately, but after Capital has verified all tables are correctly initialized. We only guarantee that it will run before your next call of Capital::api() runs.

**Comment by XanderID** [comment]
ok maybe later i will fix it better.

**Comment by XanderID** [comment]
I've moved it, thanks for the advice ^_^
