### ISSUE TITLE
startup error

### ISSUE THREAD

**Issue by jaylac2000** [XanderID-MC/EconomyEnchant#7]
[15:57:22.305] [Server thread/INFO]: Enabling EconomyEnchant v1.0.3
[15:57:22.312] [Server thread/CRITICAL]: Error: "Call to undefined method pocketmine\item\enchantment\Enchantment::getId()" (EXCEPTION) in "plugins/EconomyEnchant.phar/src/MulqiGaming64/EconomyEnchant/EconomyEnchant" at line 326
--- Stack trace ---
  #0 plugins/EconomyEnchant.phar/src/MulqiGaming64/EconomyEnchant/EconomyEnchant(93): MulqiGaming64\EconomyEnchant\EconomyEnchant->registerVanillaCEnchant(true)
  #1 pmsrc/src/plugin/PluginBase(117): MulqiGaming64\EconomyEnchant\EconomyEnchant->onEnable()
  #2 pmsrc/src/plugin/PluginManager(448): pocketmine\plugin\PluginBase->onEnableStateChange(true)
  #3 pmsrc/src/Server(1421): pocketmine\plugin\PluginManager->enablePlugin(object MulqiGaming64\EconomyEnchant\EconomyEnchant#98799)
  #4 pmsrc/src/Server(1026): pocketmine\Server->enablePlugins(object pocketmine\plugin\PluginEnableOrder#21907)
  #5 pmsrc/src/PocketMine(305): pocketmine\Server->__construct(object BaseClassLoader#2, object pocketmine\utils\MainLogger#3, string[16] /home/container/, string[24] /home/container/plugins/)
  #6 pmsrc/src/PocketMine(328): pocketmine\server()
  #7 pmsrc(11): require(string[60] phar:///home/container/PocketMine-MP.phar/src/PocketMine.php)
--- End of exception information ---

**Comment by jaylac2000** [comment]
latest pmmp / mc as of yet

**Comment by Mintuse** [comment]
Still a thing?
